/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/compare/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Players Endpoint */
        post: operations["compare_players_endpoint_api_v1_compare_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Endpoint */
        get: operations["get_player_endpoint_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Season Endpoint */
        get: operations["get_player_season_endpoint_api_v1_players__player_id__season_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Game Endpoint */
        post: operations["predict_game_endpoint_api_v1_predict_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulate/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Game Endpoint */
        post: operations["simulate_game_endpoint_api_v1_simulate_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulate/game/play-by-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Game Play By Play Endpoint */
        post: operations["simulate_game_play_by_play_endpoint_api_v1_simulate_game_play_by_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stat Leaders Endpoint */
        get: operations["stat_leaders_endpoint_api_v1_stats_leaders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Profiles Endpoint */
        get: operations["team_profiles_endpoint_api_v1_stats_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams Endpoint */
        get: operations["list_teams_endpoint_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Profile Endpoint */
        get: operations["get_team_profile_endpoint_api_v1_teams__team_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Roster Endpoint */
        get: operations["get_team_roster_endpoint_api_v1_teams__team_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComparePlayersRequest */
        ComparePlayersRequest: {
            context: components["schemas"]["DeterministicContext"];
            /** Left Player Id */
            left_player_id: number;
            /** Right Player Id */
            right_player_id: number;
        };
        /** ComparePlayersResponse */
        ComparePlayersResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["ComparePlayersResult"];
        };
        /** ComparePlayersResult */
        ComparePlayersResult: {
            /** Left Player Id */
            left_player_id: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricComparison"];
            };
            /** Right Player Id */
            right_player_id: number;
            /** Summary */
            summary: string;
        };
        /**
         * DeterministicContext
         * @description Deterministic execution contract for all stochastic endpoints.
         */
        DeterministicContext: {
            /** Data Snapshot Id */
            data_snapshot_id: string;
            /** Model Version */
            model_version: string;
            /** Seed */
            seed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricComparison */
        MetricComparison: {
            /** Better Player Id */
            better_player_id: number;
            /** Delta Left Minus Right */
            delta_left_minus_right: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "higher_is_better" | "lower_is_better";
            /**
             * Left Source
             * @enum {string}
             */
            left_source: "real" | "synthetic";
            /** Left Value */
            left_value: number;
            /**
             * Right Source
             * @enum {string}
             */
            right_source: "real" | "synthetic";
            /** Right Value */
            right_value: number;
        };
        /** PlayByPlayEvent */
        PlayByPlayEvent: {
            /** Away Score After Play */
            away_score_after_play: number;
            /** Bases After */
            bases_after: string;
            /** Bases Before */
            bases_before: string;
            /** Batter Id */
            batter_id?: number | null;
            /** Batter Name */
            batter_name?: string | null;
            /** Batting Team Id */
            batting_team_id: number;
            /** Description */
            description: string;
            /**
             * Event
             * @enum {string}
             */
            event: "out" | "walk" | "single" | "double" | "triple" | "home_run" | "tiebreaker";
            /** Fielding Team Id */
            fielding_team_id: number;
            /**
             * Half
             * @enum {string}
             */
            half: "top" | "bottom";
            /** Home Score After Play */
            home_score_after_play: number;
            /** Home Win Probability */
            home_win_probability: number;
            /** Inning */
            inning: number;
            /** Outs After */
            outs_after: number;
            /** Outs Before */
            outs_before: number;
            /** Play Index */
            play_index: number;
            /** Runs Scored On Play */
            runs_scored_on_play: number;
        };
        /**
         * PlayerSeasonLine
         * @description One player's season line for a stat group, with the metrics computed from it.
         */
        PlayerSeasonLine: {
            /** At Bats */
            at_bats?: number | null;
            /** Doubles */
            doubles?: number | null;
            /** Fip */
            fip?: number | null;
            /** Hits */
            hits?: number | null;
            /** Home Runs */
            home_runs?: number | null;
            /** Innings Pitched */
            innings_pitched?: number | null;
            /** K Bb Ratio */
            k_bb_ratio?: number | null;
            /** Plate Appearances */
            plate_appearances?: number | null;
            /**
             * Stat Group
             * @enum {string}
             */
            stat_group: "hitting" | "pitching";
            /** Stolen Bases */
            stolen_bases?: number | null;
            /** Strikeouts */
            strikeouts?: number | null;
            /** Team Id */
            team_id?: number | null;
            /** Triples */
            triples?: number | null;
            /** Walks */
            walks?: number | null;
            /** Woba */
            woba?: number | null;
            /** Wrc Plus */
            wrc_plus?: number | null;
        };
        /** PlayerSeasonResponse */
        PlayerSeasonResponse: {
            /** Lines */
            lines: components["schemas"]["PlayerSeasonLine"][];
            player: components["schemas"]["PlayerSummary"];
            /** Season */
            season: number;
        };
        /** PlayerSummary */
        PlayerSummary: {
            /** Bats */
            bats?: string | null;
            /** Full Name */
            full_name: string;
            /** Player Id */
            player_id: number;
            /** Primary Position */
            primary_position?: string | null;
            /** Throws */
            throws?: string | null;
        };
        /** PredictGameRequest */
        PredictGameRequest: {
            /** Away Team Id */
            away_team_id: number;
            context: components["schemas"]["DeterministicContext"];
            /** Home Team Id */
            home_team_id: number;
        };
        /** PredictGameResponse */
        PredictGameResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["PredictGameResult"];
        };
        /** PredictGameResult */
        PredictGameResult: {
            /** Away Expected Runs */
            away_expected_runs: number;
            /** Away Team Id */
            away_team_id: number;
            /** Away Win Probability */
            away_win_probability: number;
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string[];
            /** Home Expected Runs */
            home_expected_runs: number;
            /** Home Team Id */
            home_team_id: number;
            /** Home Win Probability */
            home_win_probability: number;
            /**
             * Source
             * @enum {string}
             */
            source: "real" | "synthetic";
        };
        /** ResponseMeta */
        ResponseMeta: {
            context: components["schemas"]["DeterministicContext"];
            /**
             * Generated At Utc
             * Format: date-time
             */
            generated_at_utc?: string;
        };
        /** SimulateGamePlayByPlayResponse */
        SimulateGamePlayByPlayResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["SimulateGamePlayByPlayResult"];
        };
        /** SimulateGamePlayByPlayResult */
        SimulateGamePlayByPlayResult: {
            /** Line Score Away */
            line_score_away: number[];
            /** Line Score Home */
            line_score_home: number[];
            /** Plays */
            plays: components["schemas"]["PlayByPlayEvent"][];
            summary: components["schemas"]["SimulateGameResult"];
        };
        /** SimulateGameRequest */
        SimulateGameRequest: {
            /** Away Team Id */
            away_team_id: number;
            context: components["schemas"]["DeterministicContext"];
            /** Home Team Id */
            home_team_id: number;
            /**
             * Innings
             * @default 9
             */
            innings: number;
        };
        /** SimulateGameResponse */
        SimulateGameResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["SimulateGameResult"];
        };
        /** SimulateGameResult */
        SimulateGameResult: {
            /** Assumptions */
            assumptions: string[];
            /** Away Score */
            away_score: number;
            /** Away Team Id */
            away_team_id: number;
            /** Home Score */
            home_score: number;
            /** Home Team Id */
            home_team_id: number;
            /** Innings Played */
            innings_played: number;
            /** Winner Team Id */
            winner_team_id: number;
        };
        /** StatLeader */
        StatLeader: {
            /** Full Name */
            full_name: string;
            /** Innings Pitched */
            innings_pitched?: number | null;
            /** Plate Appearances */
            plate_appearances?: number | null;
            /** Player Id */
            player_id: number;
            /** Rank */
            rank: number;
            /** Team Id */
            team_id?: number | null;
            /** Value */
            value: number;
        };
        /** StatLeadersResponse */
        StatLeadersResponse: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "higher_is_better" | "lower_is_better";
            /** Leaders */
            leaders: components["schemas"]["StatLeader"][];
            /**
             * Metric
             * @enum {string}
             */
            metric: "woba" | "wrc_plus" | "fip" | "k_bb_ratio";
            /** Qualifier */
            qualifier: string;
            /** Season */
            season: number;
        };
        /** TeamListResponse */
        TeamListResponse: {
            /** Teams */
            teams: components["schemas"]["TeamSummary"][];
        };
        /**
         * TeamProfileFactors
         * @description The seven [0, 1] matchup factors the simulator consumes.
         */
        TeamProfileFactors: {
            /** Command */
            command: number;
            /** Discipline */
            discipline: number;
            /** Offense */
            offense: number;
            /** Power */
            power: number;
            /** Prevention */
            prevention: number;
            /** Range Factor */
            range_factor: number;
            /** Speed */
            speed: number;
        };
        /** TeamProfileListResponse */
        TeamProfileListResponse: {
            /** Season */
            season: number;
            /** Teams */
            teams: components["schemas"]["TeamProfileResponse"][];
        };
        /** TeamProfileResponse */
        TeamProfileResponse: {
            /** Batters Counted */
            batters_counted: number;
            factors: components["schemas"]["TeamProfileFactors"];
            /** Pitchers Counted */
            pitchers_counted: number;
            /** Season */
            season: number;
            /**
             * Source
             * @enum {string}
             */
            source: "real" | "synthetic";
            /** Team Fip */
            team_fip?: number | null;
            /** Team Id */
            team_id: number;
            /** Team Woba */
            team_woba?: number | null;
        };
        /** TeamRosterResponse */
        TeamRosterResponse: {
            /** Players */
            players: components["schemas"]["PlayerSummary"][];
            /** Team Id */
            team_id: number;
        };
        /** TeamSummary */
        TeamSummary: {
            /** Abbreviation */
            abbreviation?: string | null;
            /** Division Name */
            division_name?: string | null;
            /** League Name */
            league_name?: string | null;
            /** Name */
            name: string;
            /** Team Id */
            team_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_players_endpoint_api_v1_compare_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparePlayersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparePlayersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_player_endpoint_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_season_endpoint_api_v1_players__player_id__season_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_game_endpoint_api_v1_predict_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_game_endpoint_api_v1_simulate_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_game_play_by_play_endpoint_api_v1_simulate_game_play_by_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateGamePlayByPlayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stat_leaders_endpoint_api_v1_stats_leaders_get: {
        parameters: {
            query?: {
                metric?: "woba" | "wrc_plus" | "fip" | "k_bb_ratio";
                season?: number | null;
                limit?: number;
                /** @description Playing-time qualifier (PA for hitting, IP for pitching). */
                minimum?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatLeadersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_profiles_endpoint_api_v1_stats_teams_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_endpoint_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamListResponse"];
                };
            };
        };
    };
    get_team_profile_endpoint_api_v1_teams__team_id__profile_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_roster_endpoint_api_v1_teams__team_id__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRosterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
