/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams Endpoint */
        get: operations["list_teams_endpoint_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Roster Endpoint */
        get: operations["get_team_roster_endpoint_api_v1_teams__team_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Endpoint */
        get: operations["get_player_endpoint_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Players Endpoint */
        post: operations["compare_players_endpoint_api_v1_compare_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulate/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Game Endpoint */
        post: operations["simulate_game_endpoint_api_v1_simulate_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulate/game/play-by-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Game Play By Play Endpoint */
        post: operations["simulate_game_play_by_play_endpoint_api_v1_simulate_game_play_by_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Game Endpoint */
        post: operations["predict_game_endpoint_api_v1_predict_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComparePlayersRequest */
        ComparePlayersRequest: {
            /** Left Player Id */
            left_player_id: number;
            /** Right Player Id */
            right_player_id: number;
            context: components["schemas"]["DeterministicContext"];
        };
        /** ComparePlayersResponse */
        ComparePlayersResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["ComparePlayersResult"];
        };
        /** ComparePlayersResult */
        ComparePlayersResult: {
            /** Left Player Id */
            left_player_id: number;
            /** Right Player Id */
            right_player_id: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricComparison"];
            };
            /** Summary */
            summary: string;
        };
        /**
         * DeterministicContext
         * @description Deterministic execution contract for all stochastic endpoints.
         */
        DeterministicContext: {
            /** Seed */
            seed: number;
            /** Model Version */
            model_version: string;
            /** Data Snapshot Id */
            data_snapshot_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricComparison */
        MetricComparison: {
            /** Left Value */
            left_value: number;
            /** Right Value */
            right_value: number;
            /** Delta Left Minus Right */
            delta_left_minus_right: number;
            /** Better Player Id */
            better_player_id: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "higher_is_better" | "lower_is_better";
        };
        /** PlayByPlayEvent */
        PlayByPlayEvent: {
            /** Play Index */
            play_index: number;
            /** Inning */
            inning: number;
            /**
             * Half
             * @enum {string}
             */
            half: "top" | "bottom";
            /** Batting Team Id */
            batting_team_id: number;
            /** Fielding Team Id */
            fielding_team_id: number;
            /**
             * Event
             * @enum {string}
             */
            event: "out" | "walk" | "single" | "double" | "triple" | "home_run" | "tiebreaker";
            /** Outs Before */
            outs_before: number;
            /** Outs After */
            outs_after: number;
            /** Bases Before */
            bases_before: string;
            /** Bases After */
            bases_after: string;
            /** Runs Scored On Play */
            runs_scored_on_play: number;
            /** Home Score After Play */
            home_score_after_play: number;
            /** Away Score After Play */
            away_score_after_play: number;
            /** Description */
            description: string;
            /** Batter Id */
            batter_id?: number | null;
            /** Batter Name */
            batter_name?: string | null;
        };
        /** PlayerSummary */
        PlayerSummary: {
            /** Player Id */
            player_id: number;
            /** Full Name */
            full_name: string;
            /** Primary Position */
            primary_position?: string | null;
            /** Bats */
            bats?: string | null;
            /** Throws */
            throws?: string | null;
        };
        /** PredictGameRequest */
        PredictGameRequest: {
            /** Home Team Id */
            home_team_id: number;
            /** Away Team Id */
            away_team_id: number;
            context: components["schemas"]["DeterministicContext"];
        };
        /** PredictGameResponse */
        PredictGameResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["PredictGameResult"];
        };
        /** PredictGameResult */
        PredictGameResult: {
            /** Home Team Id */
            home_team_id: number;
            /** Away Team Id */
            away_team_id: number;
            /** Home Win Probability */
            home_win_probability: number;
            /** Away Win Probability */
            away_win_probability: number;
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string[];
        };
        /** ResponseMeta */
        ResponseMeta: {
            /**
             * Generated At Utc
             * Format: date-time
             */
            generated_at_utc?: string;
            context: components["schemas"]["DeterministicContext"];
        };
        /** SimulateGamePlayByPlayResponse */
        SimulateGamePlayByPlayResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["SimulateGamePlayByPlayResult"];
        };
        /** SimulateGamePlayByPlayResult */
        SimulateGamePlayByPlayResult: {
            summary: components["schemas"]["SimulateGameResult"];
            /** Line Score Home */
            line_score_home: number[];
            /** Line Score Away */
            line_score_away: number[];
            /** Plays */
            plays: components["schemas"]["PlayByPlayEvent"][];
        };
        /** SimulateGameRequest */
        SimulateGameRequest: {
            /** Home Team Id */
            home_team_id: number;
            /** Away Team Id */
            away_team_id: number;
            /**
             * Innings
             * @default 9
             */
            innings: number;
            context: components["schemas"]["DeterministicContext"];
        };
        /** SimulateGameResponse */
        SimulateGameResponse: {
            meta: components["schemas"]["ResponseMeta"];
            result: components["schemas"]["SimulateGameResult"];
        };
        /** SimulateGameResult */
        SimulateGameResult: {
            /** Home Team Id */
            home_team_id: number;
            /** Away Team Id */
            away_team_id: number;
            /** Innings Played */
            innings_played: number;
            /** Home Score */
            home_score: number;
            /** Away Score */
            away_score: number;
            /** Winner Team Id */
            winner_team_id: number;
            /** Assumptions */
            assumptions: string[];
        };
        /** TeamListResponse */
        TeamListResponse: {
            /** Teams */
            teams: components["schemas"]["TeamSummary"][];
        };
        /** TeamRosterResponse */
        TeamRosterResponse: {
            /** Team Id */
            team_id: number;
            /** Players */
            players: components["schemas"]["PlayerSummary"][];
        };
        /** TeamSummary */
        TeamSummary: {
            /** Team Id */
            team_id: number;
            /** Name */
            name: string;
            /** Abbreviation */
            abbreviation?: string | null;
            /** League Name */
            league_name?: string | null;
            /** Division Name */
            division_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_teams_endpoint_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamListResponse"];
                };
            };
        };
    };
    get_team_roster_endpoint_api_v1_teams__team_id__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRosterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_endpoint_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_players_endpoint_api_v1_compare_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparePlayersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparePlayersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_game_endpoint_api_v1_simulate_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_game_play_by_play_endpoint_api_v1_simulate_game_play_by_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateGamePlayByPlayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_game_endpoint_api_v1_predict_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
